name: my_workflow
on:
    push: 
        branches: [main]
    workflow_dispatch:

jobs:
    cowsay:
        runs-on: ubuntu-latest
        steps:
        - 
            name: Say Hello
            run: echo 'hello'
        - 
            name: Cowsay hello
            run: |
                sudo apt install cowsay
                cowsay Hello