name: my_workflow_with_action_predefinies
on:
    push: 
        branches: [ main ]
    workflow_dispatch:

jobs:
    cowsay:
        runs-on: ubuntu-latest
        steps:
        - 
            name: Cowsay hello
            uses: mscoutermarsh/cowsays-action@master
            with:
                text: 'ship ship ship!'
                color: 'red'