name: my_workflow_with_env_from_github_action
on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - 
            name: toutes les variables d'environnement disponibles
            run: env | sort
        - 
            name: Dump github context
            run: echo '${{ toJSON(github) }}'
        - 
            name: Show variables
            run: |
                echo "OS: ${{ runner.os }}"
                echo "$GITHUB_REPOSITORY"